### ISSUE TITLE
Wybór języka strony jest niewidoczny

### ISSUE THREAD

**Issue by mutipg** [openstreetmap-polska/ua-2022-map#1]
Można zmienić kolor czcionki wyboru języka, bo w tej chwili opis pojawia się dopiero po najechaniu na niego kursorem (na obrazku kursor był nad 'PL' i dlatego go widać.
![image](https://user-images.githubusercontent.com/10333015/155767725-22baa2a2-0222-4e89-afed-0ba3537f3370.png)

**Comment by mutipg** [comment]
Chyba ustaliłem gdzie kryje się problem. W CSS https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css ostylowanie elementów 'a' posiada poniższy kod:
`a {
    color: #485fc7;
    cursor: pointer;
    text-decoration: none;
}`
kolor czcionki #485fc7 jest taki sam jak kolor tła. W inspektorze kodu zmieniłem mu z palca kolor na #4a4a4a i wybór języka jest widoczny. Może wystarczy zmienić tło dla paska. Ten CSS jest zasysany chyba z zewnętrznego źródła. Ewentualnie dodatkowym CSSem nadpisać ustawienie dla elementów 'a'. Może zaproponuję to pull requestem o ile mi się uda :)
![image](https://user-images.githubusercontent.com/10333015/155771817-fd1e2251-f569-44a2-9c63-f7c7eb41a9e1.png)

**Comment by mutipg** [comment]
https://github.com/openstreetmap-polska/ua-2022-map/pull/2

**Comment by mutipg** [comment]
Logo z flagą jest lepsze - zamykam issue :)

**Comment by Ancymonek** [comment]
Byłem szybszy :)
