### ISSUE TITLE
Slovakia emergency temporary camp (ETC)

### ISSUE THREAD

**Issue by pratikyadav** [openstreetmap-polska/ua-2022-map#21]
https://gist.github.com/pratikyadav/c404426822cdc2cf23a7d58649604a71

I was searching for shelters/emergency temporary camp (ETC) from Slovakia government, and manually mapped identified cities in their press release and social media. 

source
- https://www.minv.sk/?tlacove-spravy&sprava=pri-hranicnych-priechodoch-s-ukrajinou-v-nedelu-zacnu-zriadovat-hotspoty-pre-urychlenie-administrativneho-procesu-prichodzich-z-ukrajiny
- https://www.facebook.com/ministerstvovnutraSR/

**Comment by Mordechai23** [comment]
Hello, 
have you or someone else added those to OSM yet? 
Either way, we should establish unified tagging sheme and then we would definitely like to add those to dopomoha.pl

**Comment by Mordechai23** [comment]
Also we don't have anyone in the team proficient in Slovak language and geography enough to make something with the rough list of towns you provided. If you or someone from the local community could come up with a list/geojson of exact locations of said points, we'd be able to proceed ASAP

**Comment by pratikyadav** [comment]
> have you or someone else added those to OSM yet?
No, I have not added them as the exact locations of these hotspots was not made public by the Slovakia authorities. 

 > If you or someone from the local community could come up with a list/geojson of exact locations of said points, we'd be able to proceed ASAP
 
 
 Here is a geojson of these location mapped manually http://geojson.io/#id=gist:pratikyadav/c404426822cdc2cf23a7d58649604a71&map=10/48.7367/22.1629 
 
 I'll try to find someone from Slovakia OSM community that can add more.

**Comment by Mordechai23** [comment]
Social facilities in Slovakia now show up on map
