### ISSUE TITLE
list reception points in other countries along border, or link similar projects

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/ua-2022-map#25]
Idea from En Discord

> There are a lot of people who flee to Slovenia, Hungary and Romania. It might be a good idea to team up with them to provide more information on such POIs.

**Comment by ttomasz** [comment]
related to #21

**Comment by Mordechai23** [comment]
Added Slovakia, there seem to be no Reception Points in Hungary, Romania or Moldavia yet

**Comment by Dimitar5555** [comment]
There are 6 "regional centers of procedures and accommodation of asylum seekers" in Romania. I haven't checked if they are mapped.
https://dopomoha.ro/uk

**Comment by matkoniecz** [comment]
I opened https://github.com/openstreetmap-polska/ua-2022-map/issues/65 so it will not be lost

**Comment by matkoniecz** [comment]
@Dimitar5555 

> romanian sites are now displayed on map

https://github.com/openstreetmap-polska/ua-2022-map/issues/65#issuecomment-1058464555
