### ISSUE TITLE
github actions sprawdzający PR chyba się nie wywala przy błędach

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/ua-2022-map#3]
Jinja2 chyba zwraca tylko komunikat z logu że nie może znaleźć stringa do wypełnienia a nie wyrzuca exception

**Comment by grischard** [comment]
Do you have a sample github actions run that shows the issue? I couldn't find anything.

**Comment by ttomasz** [comment]
![image](https://user-images.githubusercontent.com/31594210/155855080-34622244-21df-4fcb-91bc-f3c2370c5ab7.png)
https://github.com/openstreetmap-polska/ua-2022-map/runs/5335831360?check_suite_focus=true
Step "generate from templates" was marked as successful despite error
