### ISSUE TITLE
Add "press ctrl+f5 to refresh" info

### ISSUE THREAD

**Issue by Mordechai23** [openstreetmap-polska/ua-2022-map#32]
Przeklejam prośbę Karola:

Ludzie ładujący stronę po raz n-ty, w tym tłumacze, mogą niewiedzieć że ładują stare dane. 

Napis "odśwież dane przy pomocy ctrl+f5" w sekcji ustawień albo gdzieś powinien pomóc

**Comment by Ancymonek** [comment]
Already added
