### ISSUE TITLE
create favicon

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/ua-2022-map#37]

**Comment by Ancymonek** [comment]
Any idea what logo/graphic we can use?

**Comment by pratikyadav** [comment]
Flag of Ukraine 

https://en.wikipedia.org/wiki/Ukrainian_People%27s_Republic#/media/File:Flag_of_Ukraine.svg

**Comment by Ancymonek** [comment]
@pratikyadav: my pull request https://github.com/openstreetmap-polska/ua-2022-map/pull/49

![obraz](https://user-images.githubusercontent.com/16021640/155951737-eab3d1f7-c348-41b4-ac47-a5d9f1989a48.png)

**Comment by Ancymonek** [comment]
Implemented in [2de5a6e004ff8ef49c8da3884d844478106a4b76](https://github.com/openstreetmap-polska/ua-2022-map/commit/2de5a6e004ff8ef49c8da3884d844478106a4b76)
