### ISSUE TITLE
add opening hours

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/ua-2022-map#43]
probably to popup

**Comment by ttomasz** [comment]
![image](https://user-images.githubusercontent.com/31594210/155905249-3d475dc9-d238-4fd4-ba7a-b563cef05503.png)
example usage of js libraryhttps://github.com/openstreetmap-polska/aed-mapa/blob/main/src/other-ui-stuff.js#L73

**Comment by Ancymonek** [comment]
added in https://github.com/openstreetmap-polska/ua-2022-map/commit/20890255e6e69f4c1172134973c3a1a76a7f550c
