### ISSUE TITLE
Wrong text is shown on the popups in Slovakia

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap-polska/ua-2022-map#51]
**Describe the bug**
The text that is shown when you click on any of the yellow nodes is about the Polish ones but it's also shown on the Slovak ones.

**To Reproduce**
1. Click on any yellow node that's in Slovakia

**Expected behavior**
Different message should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/19364673/155993515-f7b62541-5952-42bb-9cba-1d5d756c7379.png)

**Comment by Mordechai23** [comment]
Deleted incorrect description, left fixme for slovak community to add new one in slovak
