### ISSUE TITLE
Add Bulgarian coordination centers

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap-polska/ua-2022-map#52]
There currently two of them, 2 more are expected to start working this week (I will add them when they get announced). I've tagged them with `amenity=social_facility + social_facility:for=refugees`.

**Comment by Mordechai23** [comment]
It should be there now. It wasn't displayed because of a spelling error you made - correct tag is `social_facility:for=refugee` without an s

**Comment by Dimitar5555** [comment]
The mistagging is due to the use of the tags.
`social_facility:for=refugees` has 672 uses (https://taginfo.openstreetmap.org/tags/social_facility%3Afor=refugees)
`social_facility:for=refugee` has 339 uses (https://taginfo.openstreetmap.org/tags/social_facility%3Afor=refugee)

**Comment by Mordechai23** [comment]
hmmm I see. We went for `social_facility:for=refugee` because thats the tagging recommended on wiki here https://wiki.openstreetmap.org/wiki/Key:social_facility

Ill consider widening the query to include `refugees` scheme if it doesn't make the search time too long
