### ISSUE TITLE
add nominatim search bar

### ISSUE THREAD

**Issue by Mordechai23** [openstreetmap-polska/ua-2022-map#61]
**Is your feature request related to a problem? Please describe.**
we have almost 2000 place names in poland translated to ukrainian. It should be possible to search for a place name on the website

**Describe the solution you'd like**
a place name search bar, based on osm data

**Describe alternatives you've considered**
some other geographial search engine could suffice

**Comment by sabman** [comment]
@Mordechai23 I was thinking more about this and one thing to consider is to search within the geojson data that has been loaded on-to the map. But to do that in addition to the nominatim geocoder search elegantly and seamlessly would need a bit more thought. 

My initial idea is to have results displayed from nominatim and the geocoder data but show them slightly differently with some kind of a verified badge. Also if we have a side bar with a list of the search results they could be prioritised via sorting, with the verfied geojson data first then the nominatim data.

**Comment by Ancymonek** [comment]
Search box is already added.
