### ISSUE TITLE
6 "regional centers of procedures and accommodation of asylum seekers" in Romania.

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/ua-2022-map#65]
https://github.com/openstreetmap-polska/ua-2022-map/issues/25#issuecomment-1056935290

> There are 6 "regional centers of procedures and accommodation of asylum seekers" in Romania. I haven't checked if they are mapped.
https://dopomoha.ro/uk

**Comment by Mordechai23** [comment]
Ive added a Jira task for Dariusz to add them to osm
