### ISSUE TITLE
Open "layers" menu by default when entering the site

### ISSUE THREAD

**Issue by pmatejko** [openstreetmap-polska/ua-2022-map#77]
**Is your feature request related to a problem? Please describe.**
Currently when opening the site only the default layers are selected and when user may not be aware that one can hide some of them or reveal more. Also the naming may be confusing to normal people.

**Describe the solution you'd like**
We can open the "layers" menu by default. We could also change the name of it to "places".

**Describe alternatives you've considered**
`-`

**Additional context**
`-`

**Comment by Ancymonek** [comment]
If we are going to show this menu by default, it should be a bit narrower. Something like that:
![obraz](https://user-images.githubusercontent.com/16021640/156639473-b1c1f753-350a-4294-8060-0ef522083c96.png)

I

**Comment by ttomasz** [comment]
in pr #84

**Comment by Ancymonek** [comment]
Done in https://github.com/openstreetmap-polska/ua-2022-map/pull/84
