### ISSUE TITLE
Unifying contact tags (osm_data.geojson)

### ISSUE THREAD

**Issue by Ancymonek** [openstreetmap-polska/ua-2022-map#78]
**Is your feature request related to a problem? Please describe.**
In OpenStreetMap there are two ways to tag contact tags, one with prefix, for example 'contactphone' and the other - 'phone' without prefix. It applies also for all contact tags (website, email, facebook, vk etc.). Now we only render phone tag value and if it's empty contact:phone value is used. 

**Describe the solution you'd like**
Removing 'contact:' prefix in proceess_feature_properties() in download_data.py to have unified version in the entire osm_data.geojson file. Pros: file will be a bit smaller, rendering will be simpler (no need to use OR).

**Comment by kasmar00** [comment]
If there isn't anyone already working on this one, I would like to work on it.
